"""Curated taint source/sink tables for taint analysis.

This module extends the base TAINT_SOURCES / DANGEROUS_SINKS sets declared
in ``ida_mcp.tools.taint`` with broader Linux + Windows coverage that was
not historically part of the default set. The lists are designed to be:

* Conservative — only APIs that are *demonstrably* user-controlled input
  (sources) or demonstrably dangerous (sinks) are included.
* Module-agnostic — they cover glibc, POSIX, Linux syscalls, ntdll,
  wininet, winhttp, bcrypt, advapi32, kernel32, etc.
* Curated, not autogenerated — the goal is precision, not coverage.
* Designed to be extended at runtime from a BRON-style threat corpus via
  :func:`extend_taint_taxonomy_from_corpus`.

Keep entries lowercase for sources; sinks are keyed by name (case
preserved) with a "vuln_type" value.
"""
from __future__ import annotations

import re
from collections.abc import Iterable
from typing import Any, Dict, List, Set, Tuple

# ── Linux / glibc / POSIX taint sources ────────────────────────────────────────

LINUX_TAINT_SOURCES: Set[str] = {
    # Sockets / network
    "recv", "recvfrom", "recvmsg", "recvmmsg", "sendmsg", "accept", "accept4",
    "read", "pread", "preadv", "readv", "getline", "getdelim",
    # Files
    "fread", "fgets", "fgetc", "getc", "scanf", "fscanf", "sscanf", "vscanf",
    "vfscanf", "vsscanf", "wscanf", "fwscanf", "swscanf",
    # Process / argv
    "getopt", "getopt_long", "getopt_long_only",
    # Memory-mapped file reads
    "mmap",
    # Environment
    "getenv", "getenv_s", "secure_getenv",
    # stdin
    "gets", "fgetc_unlocked", "fgets_unlocked",
    # IPC
    "msgrcv", "msgrcvv", "semop",
    # Terminal / device
    "tty_read",
    # PAM / NSS / nsswitch
    "getpwnam", "getpwnam_r", "getpwuid", "getpwuid_r", "getgrnam", "getgrnam_r",
    "getgrgid", "getgrgid_r", "getspnam", "gethostbyname", "getaddrinfo",
    # DNS / resolver
    "res_query", "res_search",
    # epoll
    "epoll_wait", "epoll_pwait",
    # signalfd
    "signalfd",
    # eventfd / timerfd (read side)
    "eventfd_read",
}

# ── Windows taint sources ────────────────────────────────────────────────────

WINDOWS_TAINT_SOURCES: Set[str] = {
    # Winsock
    "recv", "recvfrom", "WSARecv", "WSARecvFrom", "WSARecvMsg",
    "WSAAccept", "WSAConnect",
    # File / console
    "ReadFile", "ReadFileEx", "ReadConsoleA", "ReadConsoleW", "ReadConsoleInputA",
    "ReadConsoleInputW", "ReadConsoleInputExA", "ReadConsoleInputExW",
    "ReadConsoleOutputA", "ReadConsoleOutputW",
    # Registry
    "RegQueryValueExA", "RegQueryValueExW", "RegGetValueA", "RegGetValueW",
    "RegEnumValueA", "RegEnumValueW", "RegQueryInfoKeyA", "RegQueryInfoKeyW",
    # Environment
    "GetEnvironmentVariableA", "GetEnvironmentVariableW", "ExpandEnvironmentStringsA",
    "ExpandEnvironmentStringsW",
    # Command line
    "GetCommandLineA", "GetCommandLineW", "CommandLineToArgvW",
    # Network
    "WinHttpReceiveResponse", "WinHttpReadData", "WinHttpQueryHeaders",
    "InternetReadFile", "InternetReadLine", "InternetQueryDataAvailable",
    "HttpSendRequestA", "HttpSendRequestW", "HttpSendRequestExA", "HttpSendRequestExW",
    "InternetOpenUrlA", "InternetOpenUrlW", "InternetConnectA", "InternetConnectW",
    # Crypto / cert
    "CryptStringToBinaryA", "CryptStringToBinaryW",
    "CertFindCertificateInStore", "CertEnumCertificatesInStore",
    # Pipe
    "PeekNamedPipe", # Mailslot
    # LPC / RPC
    "NdrClientCall2",
    # COM
    "IStream_Read",
    # WMI
    "IWbemServices_ExecQuery",
    # Crypto API user-data providers
    "CryptAcquireContextA", "CryptAcquireContextW",
    # DPAPI
    "CryptUnprotectData",
    # Pipe-based IPC
    "CallNamedPipeA", "CallNamedPipeW", "TransactNamedPipe",
}

# ── Linux / glibc / POSIX dangerous sinks ─────────────────────────────────────
# Format: api_name -> vuln_type

LINUX_DANGEROUS_SINKS: Dict[str, str] = {
    # Memory corruption
    "memcpy": "buffer_overflow",
    "memmove": "buffer_overflow",
    "memset": "buffer_overflow_candidate",
    "strcpy": "buffer_overflow",
    "strncpy": "buffer_overflow_candidate",
    "strcat": "buffer_overflow",
    "strncat": "buffer_overflow_candidate",
    "stpcpy": "buffer_overflow",
    "stpncpy": "buffer_overflow_candidate",
    "sprintf": "format_string",
    "vsprintf": "format_string",
    "snprintf": "format_string_candidate",
    "vsnprintf": "format_string_candidate",
    "gets": "buffer_overflow",
    "scanf": "buffer_overflow",
    "fscanf": "buffer_overflow",
    "sscanf": "buffer_overflow",
    "wcscpy": "buffer_overflow",
    "wcsncpy": "buffer_overflow_candidate",
    "wcscat": "buffer_overflow",
    "wmemcpy": "buffer_overflow",
    "realpath": "path_traversal",
    "readlink": "path_traversal",
    "getwd": "path_traversal",
    "chroot": "privilege_escalation",
    # Format strings
    "wprintf": "format_string",
    "fwprintf": "format_string",
    "swprintf": "format_string_candidate",
    # Command
    "system": "command_injection",
    "execve": "command_injection",
    "execvp": "command_injection",
    "execvpe": "command_injection",
    "execv": "command_injection",
    "execl": "command_injection",
    "execle": "command_injection",
    "execlp": "command_injection",
    "fexecve": "command_injection",
    "popen": "command_injection",
    "posix_spawn": "command_injection",
    "posix_spawnp": "command_injection",
    # Memory mapping / RWX
    "mmap": "memory_control",
    "mprotect": "memory_control",
    # Network output (attacker data exfil)
    "send": "network_egress",
    "sendto": "network_egress",
    "sendmsg": "network_egress",
    "write": "filesystem_write",
    "pwrite": "filesystem_write",
    "writev": "filesystem_write",
    "pwritev": "filesystem_write",
    "fwrite": "filesystem_write",
    "fputs": "filesystem_write",
    "fputc": "filesystem_write",
    "puts": "filesystem_write",
    # Privilege / setuid
    "setuid": "privilege_escalation",
    "seteuid": "privilege_escalation",
    "setresuid": "privilege_escalation",
    "setgid": "privilege_escalation",
    "setregid": "privilege_escalation",
    "setresgid": "privilege_escalation",
    "setgroups": "privilege_escalation",
    # Symlink
    "symlink": "filesystem_write",
    "link": "filesystem_write",
    "rename": "filesystem_write",
    "renameat": "filesystem_write",
    "renameat2": "filesystem_write",
    # Shell
    "wordexp": "command_injection",
    # PAM
    "pam_open_session": "privilege_escalation",
    "pam_authenticate": "privilege_escalation",
    # dlopen
    "dlopen": "dynamic_loading",
    "dlsym": "dynamic_loading",
    # File delete
    "unlink": "filesystem_write",
    "unlinkat": "filesystem_write",
    "remove": "filesystem_write",
    "rmdir": "filesystem_write",
    # chown
    "chown": "filesystem_write",
    "fchown": "filesystem_write",
    "lchown": "filesystem_write",
    "fchownat": "filesystem_write",
    # umask
    "umask": "filesystem_write",
    # mount
    "mount": "privilege_escalation",
    "umount": "privilege_escalation",
    "umount2": "privilege_escalation",
}

# ── Windows dangerous sinks ──────────────────────────────────────────────────

WINDOWS_DANGEROUS_SINKS: Dict[str, str] = {
    # String ops
    "lstrcpyA": "buffer_overflow",
    "lstrcpyW": "buffer_overflow",
    "lstrcpynA": "buffer_overflow_candidate",
    "lstrcpynW": "buffer_overflow_candidate",
    "lstrcatA": "buffer_overflow",
    "lstrcatW": "buffer_overflow",
    "StrCpyA": "buffer_overflow",
    "StrCpyW": "buffer_overflow",
    "StrCatA": "buffer_overflow",
    "StrCatW": "buffer_overflow",
    "StringCchCopyA": "buffer_overflow_candidate",
    "StringCchCopyW": "buffer_overflow_candidate",
    "StringCbCopyA": "buffer_overflow_candidate",
    "StringCbCopyW": "buffer_overflow_candidate",
    "StringCchCatA": "buffer_overflow_candidate",
    "StringCchCatW": "buffer_overflow_candidate",
    "wsprintfA": "format_string",
    "wsprintfW": "format_string",
    "wvsprintfA": "format_string",
    "wvsprintfW": "format_string",
    "wnsprintfA": "format_string_candidate",
    "wnsprintfW": "format_string_candidate",
    "PathCombineA": "path_traversal",
    "PathCombineW": "path_traversal",
    "PathAppendA": "path_traversal",
    "PathAppendW": "path_traversal",
    # Process
    "CreateProcessA": "command_injection",
    "CreateProcessW": "command_injection",
    "CreateProcessAsUserA": "command_injection",
    "CreateProcessAsUserW": "command_injection",
    "CreateProcessWithLogonW": "command_injection",
    "ShellExecuteA": "command_injection",
    "ShellExecuteW": "command_injection",
    "ShellExecuteExA": "command_injection",
    "ShellExecuteExW": "command_injection",
    "WinExec": "command_injection",
    "system": "command_injection",
    "_wsystem": "command_injection",
    "exec": "command_injection",
    "execve": "command_injection",
    "popen": "command_injection",
    "_popen": "command_injection",
    "LoadLibraryA": "dynamic_loading",
    "LoadLibraryW": "dynamic_loading",
    "LoadLibraryExA": "dynamic_loading",
    "LoadLibraryExW": "dynamic_loading",
    "GetProcAddress": "dynamic_loading",
    "GetModuleHandleA": "dynamic_loading",
    "GetModuleHandleW": "dynamic_loading",
    # Memory
    "VirtualAlloc": "memory_control",
    "VirtualAllocEx": "process_injection",
    "VirtualProtect": "memory_control",
    "VirtualProtectEx": "process_injection",
    "WriteProcessMemory": "process_injection",
    "NtAllocateVirtualMemory": "memory_control",
    "NtProtectVirtualMemory": "memory_control",
    "NtWriteVirtualMemory": "process_injection",
    "HeapAlloc": "memory_control",
    "RtlAllocateHeap": "memory_control",
    # Registry (persistence / config write)
    "RegSetValueExA": "registry_write",
    "RegSetValueExW": "registry_write",
    "RegCreateKeyExA": "registry_write",
    "RegCreateKeyExW": "registry_write",
    "RegDeleteKeyA": "registry_write",
    "RegDeleteKeyW": "registry_write",
    "RegDeleteValueA": "registry_write",
    "RegDeleteValueW": "registry_write",
    # File
    "CreateFileA": "filesystem_write",
    "CreateFileW": "filesystem_write",
    "WriteFile": "filesystem_write",
    "WriteFileEx": "filesystem_write",
    "DeleteFileA": "filesystem_write",
    "DeleteFileW": "filesystem_write",
    "MoveFileA": "filesystem_write",
    "MoveFileW": "filesystem_write",
    "MoveFileExA": "filesystem_write",
    "MoveFileExW": "filesystem_write",
    "CopyFileA": "filesystem_write",
    "CopyFileW": "filesystem_write",
    "CopyFileExA": "filesystem_write",
    "CopyFileExW": "filesystem_write",
    "SetFilePointer": "filesystem_write",
    "SetEndOfFile": "filesystem_write",
    # Service
    "CreateServiceA": "persistence",
    "CreateServiceW": "persistence",
    "StartServiceA": "persistence",
    "StartServiceW": "persistence",
    "OpenSCManagerA": "persistence",
    "OpenSCManagerW": "persistence",
    # Crypto
    "CryptEncrypt": "crypto_sink",
    "CryptDecrypt": "crypto_sink",
    "CryptHashData": "crypto_sink",
    "BCryptEncrypt": "crypto_sink",
    "BCryptDecrypt": "crypto_sink",
    "BCryptHashData": "crypto_sink",
    "BCryptOpenAlgorithmProvider": "crypto_sink",
    "NCryptEncrypt": "crypto_sink",
    "NCryptDecrypt": "crypto_sink",
    # Network
    "send": "network_egress",
    "WSASend": "network_egress",
    "WSASendTo": "network_egress",
    "WinHttpSendRequest": "network_egress",
    "InternetWriteFile": "network_egress",
    "HttpAddRequestHeadersA": "network_egress",
    "HttpAddRequestHeadersW": "network_egress",
    # Token / privilege
    "OpenProcessToken": "privilege_escalation",
    "AdjustTokenPrivileges": "privilege_escalation",
    "LookupPrivilegeValueA": "privilege_escalation",
    "LookupPrivilegeValueW": "privilege_escalation",
    "LogonUserA": "privilege_escalation",
    "LogonUserW": "privilege_escalation",
    # DPAPI
    "CryptProtectData": "crypto_sink",
    # RPC
    "RpcBindingFromStringBindingA": "dynamic_loading",
    "RpcBindingFromStringBindingW": "dynamic_loading",
    # DNS / network
    "getaddrinfo": "network_egress",
    "GetAddrInfoExA": "network_egress",
    "GetAddrInfoExW": "network_egress",
    "GetHostByNameA": "network_egress",
    "GetHostByNameW": "network_egress",
    # Privilege / SD
    "SetSecurityDescriptorDacl": "privilege_escalation",
    "SetSecurityDescriptorSacl": "privilege_escalation",
    "ConvertStringSecurityDescriptorToSecurityDescriptorA": "privilege_escalation",
    "ConvertStringSecurityDescriptorToSecurityDescriptorW": "privilege_escalation",
}

# ── Runtime extensions from a threat corpus ──────────────────────────────────

_TAINT_SOURCES_EXTRA: Set[str] = set()
_DANGEROUS_SINKS_EXTRA: Dict[str, str] = {}
_YARA_TAINT_PATTERNS: Dict[str, str] = {}


def reset_taxonomy() -> None:
    """Clear all corpus-derived taint entries. Does not touch the curated tables."""
    _TAINT_SOURCES_EXTRA.clear()
    _DANGEROUS_SINKS_EXTRA.clear()
    _YARA_TAINT_PATTERNS.clear()


def get_extra_sinks() -> Dict[str, str]:
    return dict(_DANGEROUS_SINKS_EXTRA)


# ── Corpus → taxonomy extension ──────────────────────────────────────────────

# Pattern to extract ASCII/wide string literals from a YARA rule source
_YARA_STRING_LITERAL_RE = re.compile(
    r"""(?P<kind>"s?"|")(?P<value>(?:\\.|(?!(?P=kind))[^"\\])*)(?P=kind)|"""
    r"""(?P<w>/[^/\n\r]*/)""",
    re.DOTALL,
)
_YARA_HEX_TOKEN_RE = re.compile(r"\b[0-9A-Fa-f]{2,}(?: [0-9A-Fa-f]{2}){2,}\b")
# Common Windows API substring hints (used to triage YARA string literals)
_API_HINT_TOKENS = {
    # Windows
    "CreateProcess", "ShellExecute", "WinExec", "LoadLibrary", "GetProcAddress",
    "VirtualAlloc", "WriteProcessMemory", "CreateRemoteThread", "NtCreateThreadEx",
    "RegSetValue", "RegCreateKey", "CreateService", "OpenSCManager",
    "InternetOpen", "InternetConnect", "HttpSendRequest", "WinHttpOpen",
    "WSASocket", "WSAConnect", "WSARecv", "WSASend",
    "CryptEncrypt", "CryptDecrypt", "BCryptEncrypt", "BCryptDecrypt",
    "AdjustTokenPrivileges", "LookupPrivilegeValue", "LogonUser",
    "SetWindowsHookEx", "CreateToolhelp32Snapshot",
    "DeleteFile", "MoveFileEx", "CreateFile", "WriteFile",
    # Linux
    "system", "execve", "popen", "dlopen", "mmap", "mprotect",
    "recv", "recvfrom", "send", "sendto", "read", "write",
    "chroot", "setuid", "setgid", "mount",
}


def _extract_yara_string_literals(rule_source: str) -> List[str]:
    if not rule_source:
        return []
    out: List[str] = []
    for m in _YARA_STRING_LITERAL_RE.finditer(rule_source):
        value = m.group("value") or ""
        if value:
            out.append(value)
    return out


def extend_taint_taxonomy_from_corpus(
    corpus: Any,
    *,
    reset: bool = True,
    max_yara_rules: int = 2000,
    max_added_sources: int = 200,
    max_added_sinks: int = 400,
) -> Dict[str, int]:
    """Extend the taint taxonomy from YARA rules in a BRON-style corpus.

    Strategy:
      * For each YARA rule source, extract ASCII string literals and look
        for known API name hints (e.g. "CreateProcess", "execve").
      * If the rule source mentions such an API, add the API name to the
        dangerous-sink set with ``vuln_type="yara_match"`` so the user can
        see which APIs the rule flags in the binary.
      * Returns counts of how many sources/sinks were added. The
        ``yara_match`` vuln_type makes the rule a sink candidate (if a
        binary actually contains that API, the rule is more likely to
        fire).

    The corpus-derived *sources* extension is intentionally conservative:
    YARA rules typically describe what a binary *contains*, not what
    external input it consumes. Use the curated Linux/Windows source
    tables in :data:`LINUX_TAINT_SOURCES` and :data:`WINDOWS_TAINT_SOURCES`
    for the source side.
    """
    if corpus is None:
        return {"sources": 0, "sinks": 0, "yara_rules_scanned": 0}
    if reset:
        reset_taxonomy()
    added_sources = 0
    added_sinks = 0
    yara_scanned = 0
    for rule in list(corpus.yara_rules or [])[:max_yara_rules]:
        yara_scanned += 1
        source = (rule.get("source") or "").strip()
        if not source:
            continue
        for lit in _extract_yara_string_literals(source):
            for hint in _API_HINT_TOKENS:
                if hint in lit and hint not in _DANGEROUS_SINKS_EXTRA:
                    _DANGEROUS_SINKS_EXTRA[hint] = "yara_match"
                    added_sinks += 1
                    if added_sinks >= max_added_sinks:
                        break
            if added_sinks >= max_added_sinks:
                break
        if added_sinks >= max_added_sinks:
            break
    return {
        "sources": added_sources,
        "sinks": added_sinks,
        "yara_rules_scanned": yara_scanned,
    }


def apply_curated_taxonomy(
    base_sources: Iterable[str],
    base_sinks: Dict[str, str],
) -> Tuple[Set[str], Dict[str, str]]:
    """Return (sources, sinks) merged with both curated Linux+Windows tables
    and any corpus-derived extras. Use this from taint tools that want a
    one-shot merged view."""
    sources = set(base_sources) | set(_TAINT_SOURCES_EXTRA) | set(LINUX_TAINT_SOURCES) | set(WINDOWS_TAINT_SOURCES)
    sinks = dict(base_sinks)
    for k, v in _DANGEROUS_SINKS_EXTRA.items():
        sinks.setdefault(k, v)
    for k, v in LINUX_DANGEROUS_SINKS.items():
        sinks.setdefault(k, v)
    for k, v in WINDOWS_DANGEROUS_SINKS.items():
        sinks.setdefault(k, v)
    return sources, sinks
