#!/usr/bin/env python3
"""
Host package initialization — re-exports all public APIs.
"""
from .config import (
    CACHE_DIR,
    BRIDGE_LOG,
    RUNTIME_LEASE_TTL,
    RUNTIME_LEASE_HEARTBEAT_SECONDS,
    PROCESS_TERMINATION_TIMEOUT_SECONDS,
    SEMANTIC_INDEX_VERSION,
    SEMANTIC_INDEX_DB_NAME,
    SEMANTIC_INDEX_MAX_WORKERS,
    SEMANTIC_INDEX_WAIT_SECONDS,
    SEMANTIC_GADGET_SOURCE_ACTIONS,
    SEMANTIC_INDEX_SOURCE_LIMIT,
    SEMANTIC_SCORE_SUBSTRING_MATCH,
    SEMANTIC_SCORE_PATTERN_MATCH,
    SEMANTIC_SCORE_PER_TOKEN,
    SEMANTIC_INDEX_MAX_QUERY_WORKERS,
    log_rpc,
    _bounded_int,
    _coerce_bool,
    _env_bool,
    _parse_str_list,
    _parse_line_range,
    _normalize_session_id,
    _parse_iso_datetime,
    _select_runtime_dir,
    _resolve_runtime_dir,
    _default_runtime_dir,
    validate_path,
)

from .errors import MCPError, make_error

from .analysis.patterns import compile_smart_pattern, smart_match

from .schemas import (
    TOOLS,
    TOOL_DESCRIPTIONS,
    TOOL_ACTIONS,
    TOOL_ARG_SCHEMAS,
    TOOL_ALIASES,
    ARG_ALIASES_BY_TOOL,
    ACTION_ALIASES_BY_TOOL,
    ADVERTISED_TOOLS,
    HIDDEN_TOOLS_IN_LIST,
    _resolve_tool_alias,
    _strip_balanced_wrappers,
    build_input_schema,
    build_input_schema_lean,
    build_input_schema_ultra,
    build_tool_description_ultra,
    build_tool_description_lean,
    classify_tool_category,
    sanitize_schema_for_vertex,
)

from .server.server import IDAMCPServer
from .stores.truncation import truncate_response, continue_truncated

__all__ = [
    "CACHE_DIR",
    "BRIDGE_LOG",
    "RUNTIME_LEASE_TTL",
    "RUNTIME_LEASE_HEARTBEAT_SECONDS",
    "PROCESS_TERMINATION_TIMEOUT_SECONDS",
    "SEMANTIC_INDEX_VERSION",
    "SEMANTIC_INDEX_DB_NAME",
    "SEMANTIC_INDEX_MAX_WORKERS",
    "SEMANTIC_INDEX_WAIT_SECONDS",
    "SEMANTIC_GADGET_SOURCE_ACTIONS",
    "SEMANTIC_INDEX_SOURCE_LIMIT",
    "SEMANTIC_SCORE_SUBSTRING_MATCH",
    "SEMANTIC_SCORE_PATTERN_MATCH",
    "SEMANTIC_SCORE_PER_TOKEN",
    "SEMANTIC_INDEX_MAX_QUERY_WORKERS",
    "log_rpc",
    "_bounded_int",
    "_coerce_bool",
    "_env_bool",
    "_parse_str_list",
    "_parse_line_range",
    "_normalize_session_id",
    "_parse_iso_datetime",
    "_select_runtime_dir",
    "_resolve_runtime_dir",
    "_default_runtime_dir",
    "validate_path",
    "MCPError",
    "make_error",
    "compile_smart_pattern",
    "smart_match",
    "TOOLS",
    "TOOL_DESCRIPTIONS",
    "TOOL_ACTIONS",
    "TOOL_ARG_SCHEMAS",
    "TOOL_ALIASES",
    "ARG_ALIASES_BY_TOOL",
    "ACTION_ALIASES_BY_TOOL",
    "ADVERTISED_TOOLS",
    "HIDDEN_TOOLS_IN_LIST",
    "_resolve_tool_alias",
    "_strip_balanced_wrappers",
    "build_input_schema",
    "build_input_schema_lean",
    "build_input_schema_ultra",
    "build_tool_description_ultra",
    "build_tool_description_lean",
    "classify_tool_category",
    "sanitize_schema_for_vertex",
    "IDAMCPServer",
    "truncate_response",
    "continue_truncated",
]
