#!/usr/bin/env python3
"""Alias hint registries for tool/action/arg normalization."""

_ACTION_ALIAS_HINTS = {
    "add": {"append", "insert", "create"},
    "analyze": {"analyse", "inspect"},
    "bookmarks": {"marks"},
    "callers": {"incoming_calls", "who_calls"},
    "callees": {"outgoing_calls", "calls"},
    "comment": {"set_comment", "annotate"},
    "create": {"new", "make"},
    "decompile": {"pseudo", "pseudocode"},
    "delete": {"remove", "rm", "del"},
    "disasm": {"asm", "assembly", "disassemble", "listing"},
    "entrypoints": {"entries"},
    "export": {"dump"},
    "find": {"search", "query", "lookup"},
    "functions": {"funcs", "function_list"},
    "get": {"show", "view", "read", "info"},
    "health": {"diagnostics", "diag"},
    "imports": {"imports_list"},
    "info": {"details", "describe"},
    "list": {"ls", "enumerate", "all"},
    "lookup": {"resolve", "find_addr", "find_address"},
    "meta": {"metadata"},
    "name": {"symbol"},
    "plugin_list": {"plugins", "list_plugins"},
    "plugin_run": {"run_plugin", "exec_plugin"},
    "read": {"load"},
    "regex": {"regexp"},
    "rename": {"set_name"},
    "run": {"execute", "exec"},
    "search": {"find", "query", "lookup"},
    "set_attr": {"set_attribute"},
    "set_flags": {"flags"},
    "set_options": {"configure"},
    "set_perms": {"permissions", "set_permissions"},
    "status": {"state"},
    "strings": {"strs"},
    "summary": {"overview"},
    "switch": {"use"},
    "write": {"save"},
    "xrefs_from": {"refs_from", "xrefs_out"},
    "xrefs_to": {"refs_to", "xrefs_in"},
}

_COMMON_ARG_ALIAS_HINTS = {
    "action": {"cmd", "command", "op", "operation", "tool_action"},
    "addr": {"address", "ea", "va", "offset"},
    "addrs": {"addr", "address", "addresses", "ea", "eas", "vas"},
    "binary_path": {"binary", "file", "path", "target"},
    "calls": {"steps", "requests"},
    "count": {"limit", "max", "max_items", "n"},
    "data": {"payload", "value"},
    "end": {"end_addr", "stop", "to"},
    "idb": {"database"},
    "limit": {"count", "max", "max_items", "n"},
    "max_items": {"limit", "count", "max", "n"},
    "name": {"func_name", "symbol", "label"},
    "notes": {"description"},
    "offset": {"skip"},
    "pattern": {"query", "needle", "match"},
    "query": {"q", "search", "pattern"},
    "session_id": {"sid", "session"},
    "start": {"from", "start_addr"},
    "target": {"to"},
    "topic": {"doc", "page"},
}

_TOOL_SPECIFIC_ARG_ALIASES = {
    "code": {
        "addrs": {"addr", "address", "addresses", "ea", "eas"},
        "max_items": {"count", "max"},
    },
    "data": {
        "query": {"name", "symbol", "lookup"},
    },
    "search": {
        "pattern": {"query", "needle"},
    },
    "segments": {
        "start": {"address", "addr", "ea", "segment"},
        "end": {"address2", "addr2", "ea2", "segment2"},
        "name": {"segment_name"},
        "name2": {"segment_name2"},
    },
}

_TOOL_ACTION_EXTRA_ALIASES = {
    "annotation": {
        "auto_comment": {"comment", "annotate", "auto_annotate"},
        "cleanup": {"clean", "sanitize", "normalize"},
        "get_context": {"context", "comments_context", "comment_context"},
        "set_structured": {"set_comment", "comment"},
        "bulk_set": {"bulk_comment", "set_many", "annotate_many"},
        "export_md": {"export_comments", "md_export"},
        "import_md": {"import_comments", "md_import"},
        "summary": {"comment_summary", "coverage_stats"},
    },
    "search": {
        "bytes": {"byte", "opcode_bytes", "hex_bytes"},
        "string": {"strings", "str", "text_string"},
        "immediate": {"imm", "immediates", "literal", "number"},
        "name": {"symbol", "symbol_name", "func_name", "named"},
        "insns": {"insn", "instruction_seq", "instruction_sequence", "asm_seq"},
        "mnemonic": {"mnemonics", "mnem", "opcode", "opcodes"},
        "instruction": {"instruction", "instructions", "instructions_text", "insn_text", "instruction_text", "asm_text", "semantic_instruction"},
        "text": {"full_text", "plaintext"},
        "operand": {"operands", "opnd", "arg_text"},
        "comment": {"comments", "cmt", "annotation", "notes"},
        "data_ref": {"data_refs", "dref", "drefs"},
        "code_ref": {"code_refs", "cref", "crefs", "xref"},
        "regex": {"regexp", "re", "pattern_regex"},
        "func_by_sig": {"signature", "sig", "func_signature", "signature_search"},
        "find": {"search", "lookup", "query", "locate", "discover"},
        "callers": {"incoming", "inbound_calls", "who_calls"},
        "callees": {"outgoing", "outbound_calls", "calls_from"},
        "api": {"apis", "import_api", "api_calls"},
        "vulnerable": {"vuln", "vulnerabilities", "risky"},
        "constants": {"const", "literals", "magic"},
        "decompiled": {"decompile", "pseudo", "pseudocode", "hl"},
    },
    "session": {
        "create": {"new", "open", "start", "init", "spawn"},
        "get": {"show", "read", "info", "details"},
        "list": {"ls", "all", "enumerate"},
        "switch": {"use", "activate", "focus"},
        "close": {"delete", "remove", "terminate", "stop"},
        "status": {"state", "current", "active"},
        "rebuild": {"refresh", "recreate", "reanalyze"},
        "update": {"set"},
        "rename": {"set_name", "retitle"},
        "duplicate": {"clone", "copy"},
        "archive": {"stash"},
        "unarchive": {"unstash"},
        "tag": {"add_tag", "label"},
        "untag": {"remove_tag", "del_tag"},
        "add_note": {"note", "append_note"},
        "clear_notes": {"wipe_notes", "reset_notes"},
        "search_notes": {"find_notes", "notes_search"},
        "snapshot": {"savepoint", "checkpoint"},
        "restore_snapshot": {"rollback", "restore"},
    },
    "code": {
        "decompile": {"decompiled", "pseudo", "pseudocode", "hl"},
        "semantic_decompile": {"deep_decompile", "semantic_ir", "decomp_semantics", "rich_decompile"},
        "decomp_dataflow": {"decompiler_dataflow", "decomp_slice", "var_flow"},
        "disasm": {"disassemble", "asm", "assembly", "listing"},
        "xrefs_to": {"xref_to", "refs_to", "incoming_refs"},
        "xrefs_from": {"xref_from", "refs_from", "outgoing_refs"},
        "xrefs_to_field": {"field_xrefs", "xrefs_field"},
        "callees": {"calls", "called_functions", "outgoing_calls"},
        "callers": {"who_calls", "incoming_calls"},
        "blocks": {"basic_blocks", "bb"},
        "callgraph": {"cg", "graph_calls"},
        "export": {"dump", "save"},
        "find_paths": {"paths", "path_search", "reachability"},
        "strings_in_func": {"func_strings", "strings"},
    },
    "ctree": {
        "dominance_map": {"dom_map", "condition_dominance", "control_dominance"},
        "var_dependency_graph": {"var_graph", "dependency_graph", "ssa_like_graph"},
    },
    "governance": {
        "check": {"evaluate", "inspect", "validate", "review"},
        "redact": {"sanitize", "scrub", "cleanse", "strip_pii"},
        "list_rules": {"rules", "show_rules", "get_rules"},
        "stats": {"statistics", "metrics", "counters"},
    },
}

