#!/usr/bin/env python3
"""Shared tool registry data for schemas.py."""
from .schemas_alias_hints import (
    _ACTION_ALIAS_HINTS,
    _COMMON_ARG_ALIAS_HINTS,
    _TOOL_ACTION_EXTRA_ALIASES,
    _TOOL_SPECIFIC_ARG_ALIASES,
)

BASE_TOOL_ALIASES = {
    "plugins": "misc",
    "xref_analysis": "graph",
    "xfer_analysis": "graph",
}

TOOLS = [
    # Core session and batch tools (host-side)
    "session",
    "truncation",
    "bookmarks",
    "batch",
    # Analysis configuration
    "analysis",
    # Unified query/edit hubs (delegating to sub-tools)
    "query",
    # Primary data access tools
    "idb",
    "code",
    "data",
    "search",
    "types",
    "memory",
    # Modification tools
    "modify",
    "funcs",
    "segments",
    "bulk",
    # Utilities
    "misc",
    "calc",
    "nav",
    # Debugging and tracing
    "debug",
    "coverage",
    "trace_analysis",
    # Project and file management
    "project",
    # Advanced analysis
    "agent",
    "microcode",
    "graph",
    "ctree",
    "entropy",
    # Structure and type recovery
    "imports_deep",
    "patterns",
    "symbols",
    # Differential and comparison
    "lumina",
    # Export and annotation
    "export",
    "history",
    "colorize",
    "data_ops",
    "firmware_view",
    # Instrumentation
    "hooks",
    # Documentation and YARA
    "wiki",
    "yara_hunt",
    # Intelligence subsystem (extracted from agent)
    "intelligence",
    # --- New LLM-optimized tools ---
    # Security & vulnerability analysis
    "threat_hunt",
    "predictor",
    "workflow",
    "gadgets",
    "taint",
    # Deobfuscation & crypto
    "deobfuscate",
    "crypto_id",
    # ABI & calling conventions
    "abi",
    # Summarization & classification
    "summarize",
    "classify",
    # Function comparison
    "compare",
    # Stack analysis
    "stack_analysis",
    # Protocol analysis
    "protocol",
    # Intelligent annotation
    "annotation",
    # String operations
    "string_ops",
    # CFG analysis
    "cfg_analysis",
    # Binary info
    "binary_info",
    # LLM helpers
    "llm_helpers",
    # Structured semantic indexing
    "schemaboot",
    # Other components
    "bridge_search",
    # --- New infrastructure tools ---
    "blackboard",
    "filter",
    # --- Governance ---
    "governance",
    # --- Cross-session firmware KB ---
    "knowledge",
    # --- Relocation/fixup management (specialized; not advertised) ---
    "fixups",
]

ADVERTISED_TOOLS = [
    "session",
    "truncation",
    "bookmarks",
    "batch",
    "wiki",
    "analysis",
    "query",
    "idb",
    "code",
    "data",
    "search",
    "imports_deep",
    "symbols",
    "patterns",
    "types",
    "memory",
    "modify",
    "funcs",
    "segments",
    "bulk",
    "misc",
    "calc",
    "nav",
    "project",
    "debug",
    "graph",
    "ctree",
    "export",
    "history",
    "annotation",
    "binary_info",
    "threat_hunt",
    "predictor",
    "workflow",
    "compare",
    "firmware_view",
    "blackboard",
    "knowledge",
    # RE-useful tools (previously hidden)
    "abi",
    "agent",
    "bridge_search",
    "cfg_analysis",
    "classify",
    "coverage",
    "crypto_id",
    "intelligence",
    "data_ops",
    "deobfuscate",
    "entropy",
    "filter",
    "gadgets",
    "governance",
    "hooks",
    "llm_helpers",
    "lumina",
    "microcode",
    "protocol",
    "stack_analysis",
    "string_ops",
    "summarize",
    "taint",
    "trace_analysis",
    "yara_hunt",
]

_EXTRA_TOOL_ALIASES = {
    "embeddings": "intelligence",
    "ai_classifier": "intelligence",
    "agent_intelligence": "intelligence",
    "analysis_tool": "analysis",
    "annotate": "annotation",
    "annotations": "annotation",
    "assembler": "code",
    "assembly": "code",
    "bookmarks_tool": "bookmarks",
    "code_tool": "code",
    "database": "idb",
    "decompiler": "code",
    "firmware": "firmware_view",
    "firmware_ops": "firmware_view",
    "firmware_view_tool": "firmware_view",
    "firmware_bootstrap": "firmware_view",
    "decomp": "code",
    "diag": "misc",
    "disasm": "code",
    "disassembly": "code",
    "fn": "funcs",
    "func": "funcs",
    "function": "funcs",
    "functions": "funcs",
    "graphs": "graph",
    "helper": "llm_helpers",
    "helpers": "llm_helpers",
    "hexrays": "code",
    "i_db": "idb",
    "ida": "idb",
    "imports": "imports_deep",
    "lookup": "data",
    "notes": "bookmarks",
    "plugins_tool": "misc",
    "python": "misc",
    "queries": "query",
    "vuln": "threat_hunt",
    "vulnerability": "threat_hunt",
    "vulnerabilities": "threat_hunt",
    "threat": "threat_hunt",
    "threat_hunt_tool": "threat_hunt",
    "malware": "threat_hunt",
    "security": "threat_hunt",
    "trace": "threat_hunt",
    "tracing": "threat_hunt",
    # NOTE: do NOT alias "coverage" here — it collides with the canonical
    # `coverage` tool. The collision is silently dropped by _build_tool_aliases
    # but the entry confuses readers. See Phase 1.5 of dedupe plan.
    "c2": "threat_hunt",
    "c2_detect": "string_ops",
    "deobfuscation": "threat_hunt",
    "crypto": "threat_hunt",
    "yara": "threat_hunt",
    "hunt": "threat_hunt",
    "automated_findings": "threat_hunt",
    "recommend": "predictor",
    "predict": "predictor",
    "next_tool": "predictor",
    "workflow_predictor": "predictor",
    # Legacy/compat aliases kept for older clients and scripts.
    "comments_ai": "annotation",
    "annotations_ai": "annotation",
    "strings_xref": "graph",
    "emulate": "trace_analysis",
    "searches": "search",
    "segment": "segments",
    "session_tool": "session",
    "strings": "string_ops",
    "symbols_tool": "symbols",
    "trace_analyze": "trace_analysis",
    "xref": "graph",
    "xrefs": "graph",
    "govern": "governance",
    "rules": "governance",
    "policy": "governance",
}

# Canonical legacy threat-route contract used by host dispatchers.
THREAT_LEGACY_REDIRECT_TOOLS = {
    "c2_detect": "string_ops",
}

THREAT_LEGACY_TRACING_TOOLS = {
    "trace",
    "trace_analysis",
    "coverage",
    "taint",
}

THREAT_LEGACY_VULN_TOOLS = {
    "gadgets",
    "search",
}

THREAT_LEGACY_MALWARE_PASSTHROUGH_TOOLS = {
    "deobfuscate",
    "crypto_id",
    "yara_hunt",
    "string_ops",
}

# Tool->optional action allowlist for legacy passthrough flows.
# `None` means any action is accepted.
THREAT_LEGACY_CONDITIONAL_PASSTHROUGH = {
    "classify": None,
    "protocol": None,
    "summarize": {
        "security_posture",
        "statistics",
        "binary",
        "function",
    },
    "agent": {
        "search_all",
        "find_references",
    },
}

TOOL_DESCRIPTIONS = {
    "abi": "Analyzes calling conventions and ABI details of functions. Actions: detect, stack_args, reg_args, return_type, varargs, struct_return, tail_calls, prologue, epilogue, abi_violations.",
    "agent": "High-level AI-assisted analysis combining search, context packing, multi-hop discovery, and CFG similarity. Actions: analyze_function, explore_address, find_references, search_all, search_structs, context_pack, quick, rename_suggestions, batch_context, similar, bridge_query, reflect, cluster, fingerprint, cfg_encode, cfg_similar, cfg_stats.",
    "analysis": "Controls IDA analysis engine settings and triggers reanalysis, and runs IDA plugins. Actions: get_options, set_options, set_processor, set_loader_options, set_architecture, reanalyze, run, analyze, wait, plugin_run.",
    "annotation": "Automatically generates and manages comments, labels, and documentation across functions. Actions: auto_comment, auto_comment_function, label_loops, label_branches, mark_dangerous, annotate_constants, tag_functions, document_args, mark_error_paths, propagate_names, cleanup, validate, get_context, set_structured, bulk_set, export_md, import_md, summary.",
    "batch": "Executes multiple tool calls in a single request to reduce round trips. Pass a calls array of tool invocations.",
    "binary_info": "Retrieves binary metadata including PE/ELF headers, sections, and build info. Actions: headers, sections, relocations, resources, debug_info, compiler, linker, timestamps, checksums, overlay.",
    "blackboard": "Firmware RE knowledge base: findings, hypotheses, IOCs, vulns, regions, and knowledge graph. write/read/list/search/update/delete/clear/prune/stats/merge: CRUD. semantic_index/semantic_rebuild: persistent semantic vector lifecycle for entries. related_by_behavior: behavior-centric semantic retrieval over stored notes. frontier: ranked unvisited functions by embedding proximity + xref + entropy (read when choosing what to analyze next). coverage: analyzed vs unvisited per embedding cluster (read to understand progress). propagate_labels: spread LLM labels to embedding-similar neighbors via FrontierEngine. next_target: priority queue (confidence × time_decay × xref_boost). contradict/resolve/add_evidence/calibrate: evidence lifecycle. campaign_summary/auto_tag_propagate: batch operations. start_crawler/stop_crawler/crawler_status/accept/reject: background xref crawler. KG actions: kg_add_system/kg_add_struct/kg_add_gap/kg_add_state_machine/kg_add_attack_surface/kg_add_peripheral + read variants.",
    "bookmarks": "Manages named address bookmarks for quick navigation and milestone tracking. Actions: add, list, delete, update, clear, find, export.",
    "bridge_search": "Multi-hop bridge-conditioned search for discovering indirect relationships between entities. Actions: search, bridges.",
    "bulk": "Applies batch edits (renames, comments, types) to multiple addresses in one call. Actions: rename, comment, apply_type, rename_stack, import_annotations, export_annotations.",
    "calc": "Safe address arithmetic and pointer resolution—use instead of mental math. Includes bitwise helper operations. Actions: eval, offset, convert, resolve, deref, chain, align, bitops.",
    "cfg_analysis": "Analyzes control flow graph structure including loops, dominators, and complexity. Actions: complexity, loops, branches, paths, dominators, post_dominators, back_edges, natural_loops, irreducible, flatten_detect.",
    "classify": "Classify functions and binaries by purpose. function: single function — embedding-driven BehaviorClassifier (bge-code-v1). binary: overall binary type. all_functions: classify all functions — unnamed functions use BehaviorClassifier. library_code/wrappers/callbacks/initializers/error_handlers: structural classification. hot_functions: most-called functions. orphans: no-caller functions (entry points / dead code). induce_schema: SchemaBoot attribute-value schema for structured retrieval. anchor_coverage: report per-anchor coverage over current IDB.",
    "code": "Decompilation, disassembly, and code analysis. smart_decompile: best single call — pseudocode + behavior_tags + api_calls + crypto_hints + dangerous_patterns + var_rename_hints + callers + callees + strings + blackboard_context + suggested_next_actions. decompile: pseudocode with inline api_calls/crypto_hints/complexity. disasm: assembly listing. analyze: comprehensive (decompile+callers+callees+strings+stack) [deprecated — use agent(analyze_function)]. decompile_chain: function with compact caller/callee context (first 8 lines each). semantic_decompile: pseudocode + CFG semantics + variable dependency graph. diff_functions: unified diff of two functions. annotate: add comment to function/address [deprecated — use modify(comment)]. xrefs_to/from, callees, callers, blocks, callgraph, find_paths, strings_in_func, decomp_dataflow, export.",
    "colorize": "Sets and queries color highlighting on functions, ranges, and instructions. Actions: set_func, set_range, set_insn, get, clear, palette, highlight_pattern.",
    "compare": "Diff two IDB databases or functions across binaries. Actions: functions, blocks, apis, strings, constants, structure, semantics, batch_compare, find_clones, changelog.",
    "coverage": "Import and analyze code coverage data to identify hit/missed paths. Actions: import_drcov, import_lighthouse, highlight, report, uncovered, filter, function_coverage, gaps, compare, merge.",
    "crypto_id": "Detect cryptographic algorithms, constants, and encoding routines in the binary. Actions: identify, constants, encoding, checksums, entropy_analysis, aes_ni.",
    "ctree": "Query and traverse the Hex-Rays decompiler ctree AST for a function. Actions: get, traverse, find_calls, find_vars, find_strings, find_conditions, get_logic_flow, dominance_map, var_dependency_graph.",
    "data": "Retrieve core IDB data. functions: list all functions — always includes xref count (capped 999). globals: global variables. strings: string literals — always includes xref count. imports: imported modules and functions. exports: exported entry points. lookup: resolve name↔address. bulk_query: multiple queries in one call. capability_matrix: binary capability matrix from imports + function classifications. string_xrefs: ranked string-to-function xref map with module clustering.",
    "data_ops": "Change data representation at addresses: define types, arrays, strings, pointers. Actions: make_data, make_array, make_string, undefine, make_code, cycle_data, set_repr (hex/dec/bin/char/offset via repr param), make_ptr.",
    "debug": "Control the debugger: run, step, breakpoints, registers, memory, threads. Actions: status, start, stop, continue, step_into, step_over, run_to, run_until, breakpoints, add_bp, del_bp, enable_bp, add_hw_bp, add_watch, regs, set_reg, reg_diff, snapshot_regs, threads, modules, callstack, read_mem, write_mem, search_mem, stack_dump, mem_map, bp_context, trace_start, trace_stop, trace_read, mem_diff.",
    "deobfuscate": "Detect and decode obfuscation: stack strings, API hashing, dead code, anti-disasm. Actions: detect, detect_encoding, stack_strings, dead_code, api_hashing, dynamic_dispatch, anti_disasm, decode_attempt.",
    "entropy": "Compute entropy over regions to detect packing, encryption, or compressed data. Actions: section, region, packed_detect, crypto_detect, compare, window, summary.",
    "export": "Export IDB content in various formats for external tooling. Actions: listing, html, idc, json, sarif, binexport, headers, redact.",
    "filter": "JQ-like deterministic filtering for tool outputs — prevents context overflow. Supports field extraction (.key), slicing ([0:10]), predicate filter ([?size > 100]), sort, unique, pluck, group_by, count, and first(N). Run any large list result through filter before returning to the LLM. Actions: filter.",
    "firmware_view": "Firmware triage: region scanning, pointer sweeps, table carving, deterministic detection logic, multi-region campaigns, and bootstrap orchestration. Actions: scan_region, auto_retype, pointer_sweep, recommend, table_candidates, smart_carve, rollback_last, review_contradictions, region_profile, pointer_clusters, carve_plan, campaign, segment_sweep, multi_region_campaign, campaign_checkpoint, campaign_resume, campaign_feedback, fingerprint_index_sync, fingerprint_index_query, detect_load_address, detect_vector_table, detect_mmio, rtos_scan, triage_snapshot, bootstrap.",
    "fixups": "Manage relocations/fixups (relocation table entries) in the IDB. Actions: list, get, add, delete.",
    "funcs": "Function boundary management with regex/glob/substring filtering. Actions: create, delete, set_flags, info, metrics, find_similar, suggest_names. (Renames/comments/listings live on modify and data.)",
    "gadgets": "Find ROP/JOP/COP gadgets, stack pivots, and classify exploit chains. Actions: rop, jop, cop, syscall, write_what_where, stack_pivot, shellcode_space, mitigations, seh_handlers, pivot_chains, classify_chain.",
    "governance": "Pre-flight validation for edits: detect contradictions, PII, dangerous patches. Actions: check, redact, list_rules, stats.",
    "knowledge": "Cross-session firmware knowledge base: chip family identification, persistent symbol memory, and symbol transfer across binaries. Actions: chip_identify, symbol_lookup, import_symbols, export_session, chip_families.",
    "graph": "Generate call graphs, CFGs, xref graphs, and cross-reference graph analysis. Actions: callgraph, cfg, dominators, xref_graph, call_chain, common_callers, common_callees, hub_functions, leaf_functions, recursive, dominator, influence, dependency_graph, dead_functions.",
    "history": "Undo/redo IDB changes, create snapshots, restore, and diff states. Actions: undo, redo, list, snapshot, restore, diff.",
    "hooks": "Generate dynamic instrumentation hooks (Frida, Detours) for target functions. Actions: suggest, generate_frida, generate_detours, find_targets, inline_hooks.",
    "idb": "Query top-level IDB metadata: binary info, segments, entrypoints, bookmarks, and architecture profile guidance for raw binaries. Actions: meta, summary, segments, entrypoints, bookmarks, overview, architecture_profile.",
    "imports_deep": "Deep import analysis: thunks, delay-loads, forwarded, ordinal, and API set resolution. Actions: thunks, delay, forwarded, ordinal, api_sets, resolve.",
    "intelligence": "Intelligence subsystem: embedding-based function classification, indexing, similarity search, and evidence-card production. Actions: intelligence_status, embedder_status, anchor_status, refresh_anchors, classify_text, classify_function, index_function, index_batch, similar_functions, semantic_search, blackboard_search, export_index_summary, evidence_card.",
    "llm_helpers": "Context-optimized helpers for LLM agents. START HERE: bootstrap gives a concrete first-turn playbook; cheatsheet returns full tool reference with concrete examples. context_window/function_digest/binary_digest/explain_address: compact analysis helpers. suggest_next/progress_report/focus_area: navigation and planning. behavioral_signature_search: find functions by behavior tag using BehaviorClassifier. function_role_classifier: entry_point/callback/dispatcher/wrapper via structural+embedding signals. dangerous_pattern_explainer: why a pattern is dangerous + exploitation path + mitigation. api_contract_extractor: infer preconditions/postconditions from call sites. global_state_influence_mapper: which globals a function reads/writes. interprocedural_data_lineage_graph: trace data flow across function boundaries. semantic_diff_explainer: embedding+BehaviorClassifier diff between two functions. decompile_disasm_consistency_search: find decompiler/disasm disagreements. argument_semantics_search: find functions by argument role. path_constrained_search: BFS from addr filtered by behavior tag. cross_artifact_correlation_search: correlate strings/names/blackboard by query.",
    "lumina": "Interface to Hex-Rays Lumina server for collaborative function metadata sharing. Actions: pull, push, status, history, search, get_metadata.",
    "memory": "Read, write, and inspect raw memory/bytes in the binary or debuggee, plus host filesystem read/write helpers. Actions: read, write, hexdump, search, compare, pointers, find_pointers, entropy, strings, struct_walk, histogram, read_file, write_file.",
    "microcode": "Access Hex-Rays microcode IR for a function at various maturity levels. Actions: get, blocks, instructions, def_use_graph.",
    "misc": "Utility grab-bag: run scripts and list loaded plugins. Actions: python, idc, load_sig, cache_stats, plugin_list. (read_file/write_file → memory, plugin_run → analysis, health → session.)",
    "modify": "Apply edits to the IDB: rename symbols, add comments (regular/repeatable/anterior/posterior), set types, and patch assembly (multi-line instructions separated by semicolons). Actions: rename, comment, set_type, patch_asm.",
    "nav": "Navigate the IDA cursor to addresses or semantically interesting locations. Actions: goto, cursor, interesting, semantic_goto.",
    "patterns": "Generate, match, and manage FLIRT/byte pattern signatures for function identification. Actions: generate, match, list_sigs, apply_sig, create_sig, matched, yara_from_func, flirt_generate, match_yara.",
    "predictor": "Deterministic prediction of next useful tool, focus address, or stuck-state detection. recommend_bundle returns a bundled next-step pack (tools + focus + addresses + stall risk). Actions: suggest_next_tool, detect_stuck, suggest_focus, suggest_next_address, risk_of_stall, recommend_bundle.",
    "project": "Project I/O and evidence management. Actions: save, close, open, load_binary, list_recent, get_cwd, set_cwd, list_dir, exists, evidence_graph, knowledge_merge, confidence_model, replay_pipeline, hypothesis_tracker, temporal_reasoning, semantic_artifact_diff, ai_governance, knowledge_debt, casefile_export.",
    "protocol": "Detect and analyze network protocol structures, parsers, endpoints, and state machines in a binary. Actions: detect, parsers, serializers, handlers, endpoints, tls_config, socket_flow, packet_struct, magic_numbers, state_machine.",
    "query": "Unified query interface combining data, search, code, types, symbols, and natural-language queries. Actions: data, search, idb, code, types, imports_deep, symbols, patterns, nl, nl_batch.",
    "schemaboot": "Structured semantic indexing with induced attribute-value schemas for function-level retrieval. Actions: ingest, query, refresh, stats, delete, get.",
    "search": "Pattern, reference, and semantic search across the binary. nl: natural language search using bge-code-v1 embeddings (most accurate for RE queries). behavior: find all functions matching a behavior tag (crypto_symmetric, network_http, etc.) via BehaviorClassifier. find: smart unified search (names/strings/imports/instructions, auto-ranked). semantic: NL search with embedding-aware ranking. smart_bundle: fused find+semantic with deduplicated structured items. api: find all usages of an imported API. decompiled: search pseudocode across all functions (auto-writes blackboard entries for matches). structured: schema-based pre-filtered search with behavior_tags constraints. vulnerable: scan for dangerous API patterns. constants: find crypto/magic constants. callers/callees, bytes/string/immediate/name/insns/mnemonic/instruction/text/operand/comment/data_ref/code_ref/regex/func_by_sig/type/export/summary/query_lang.",
    "segments": "List, create, modify, and analyze binary segments and their permissions/attributes. Actions: list, add, delete, set_attr, set_perms, move, info, analyze, find_code, find_data, compare, merge. For relocations/fixups use the dedicated `fixups` tool.",
    "session": "Full session lifecycle with runtime tracking, analysis notebook, hypothesis tracking, and skill crystallization. Actions: create/switch/close/list/status, snapshot/restore, crystallize_skill/rate_skill/suggest_strategy, notebook_append/read, track_hypothesis/confirm/refute, get_phase/advance_phase, recent_workset, macro_set/run, dashboard, health. cleanup_stale: remove sessions older than max_age_days (default 30) — run this when sessions accumulate. health: server, runtime, IDA, session, wiki, and tool-surface diagnostics (verbose=true for per-runtime breakdown).",
    "stack_analysis": "Analyze stack frames: buffer sizes, canaries, alignment, spills, variables, and uninitialized regions. Actions: frame, buffers, canary, alignment, spills, usage, variables, arrays, uninitialized, summary.",
    "string_ops": "Advanced string analysis and IOC extraction. score_c2/indicators: C2 risk report — BehaviorClassifier on strings + API triads + family guess. ioc_extract: extract all IOCs (URLs, IPs, registry keys, C2 endpoints). persistence/evasion: persistence mechanisms and evasion techniques. find_urls/find_ips/find_paths/find_registry/find_emails/find_commands: pattern extraction. find_c2/find_configs/find_api_keys/find_databases/find_crypto_addrs: semantic extraction. find_stack_strings/find_base64: obfuscated string recovery. entropy_rank: rank strings by Shannon entropy. suspicious/encoding_stats/multilingual/decode_all: analysis utilities.",
    "summarize": "Structured summaries of binary components. binary: overall binary summary. function: single function summary. segment: segment summary. imports_by_category: imports grouped by API category. strings_by_category: strings grouped by type. complexity: function complexity metrics. call_hierarchy: call tree from entry point. data_flow: data flow summary. security_posture: dangerous APIs + mitigations + risk level. statistics: binary-wide stats. report: FULL REPORT — binary + security_posture + live taint scan + blackboard findings + statistics.",
    "symbols": "Loads and manages debug symbols (PDB/DWARF) for the current binary. Actions: load_pdb, load_dwarf, status, apply, export.",
    "taint": "Data flow taint analysis from user-controlled sources to dangerous sinks. Actions: sources (list all taint sources: recv/read/fgets/getenv imports + blackboard IOCs), sinks (dangerous sinks reachable from a source), trace (trace forward from addr/source, write vuln entries to blackboard), paths (full call-graph paths source→sink with dataflow description), report (all sources → all reachable sinks). Example: taint(action='trace', source='recv') finds all paths from recv to memcpy/strcpy/system.",
    "threat_hunt": "Runs automated threat-hunting passes to detect malware patterns, vulnerabilities, and suspicious behaviors. Actions: run, malware, vuln, tracing, findings, quick, deep, legacy.",
    "trace_analysis": "Analyzes imported execution traces for coverage, loops, API sequences, and anti-analysis detection. Also provides runtime execution-trace access (get/clear/set_options) and static control-flow tracing (static_trace, decrypt_strings, eval_expr). Actions: import_trace, analyze_coverage, find_loops, extract_api_calls, basic_blocks_hit, execution_timeline_graph, cross_run_diff, coverage_debug_plan, anti_analysis_detect, trace_entropy, api_sequence, loop_analysis, get, clear, set_options, static_trace, decrypt_strings, eval_expr.",
    "truncation": "Continues a previously truncated tool response to retrieve remaining output. Actions: continue.",
    "types": "Manages IDA type system: structs, enums, prototypes, type propagation, and header imports. Actions: list, get, set_prototype, parse_decl, declare, apply, search_structs, infer, read_struct, import_header, diff, visualize, propagate, enum_values, type_graph.",
    "wiki": "Accesses built-in documentation and tool usage guides within MCP context. Actions: list_topics, read, search, semantic_search, index, sections, suggest.",
    "workflow": "Executes predefined multi-step analysis workflows for common RE tasks. audit_plan validates and scores a plan before execution. execute_plan runs a planned call list (or generated plan) through batch execution with execution metadata. prioritize reorders a dry-run plan by strategy (original/coverage/risk_first). compose merges multiple workflow plans into one deduplicated dry-run execution plan. estimate returns dry-run complexity/risk/category projections. explain returns a dry-run plan plus per-step rationale. plan previews another workflow action without executing it. catalog returns available workflows and required inputs. triage_fast auto-checks idb overview and, for firmware-like binaries, injects firmware_view(action='triage_snapshot') plus guided analysis. recon_sweep runs broader orientation + structured retrieval + protocol + security posture in one pass. Supports dry_run plan preview and include/exclude tool filtering for controlled orchestration. Actions: audit_plan, execute_plan, prioritize, compose, estimate, explain, plan, catalog, triage_fast, malware_deep, vuln_audit, recon_sweep, patch_review.",
    "yara_hunt": "Scans the binary with YARA rules and provides match context and xref correlation. Actions: scan, compile, list_rules, match_context, extract_strings, xref_matches.",
}

TOOL_ACTIONS = {
    "abi": [
        "detect",
        "stack_args",
        "reg_args",
        "return_type",
        "varargs",
        "struct_return",
        "tail_calls",
        "prologue",
        "epilogue",
        "abi_violations",
    ],
    "agent": [
        "analyze_function",
        "explore_address",
        "find_references",
        "search_all",
        "search_structs",
        "context_pack",
        "quick",
        "rename_suggestions",
        "batch_context",
        "similar",
        "bridge_query",
        "reflect",
        "cluster",
        "fingerprint",
        "cfg_encode",
        "cfg_similar",
        "cfg_stats",
    ],
    "intelligence": [
        "intelligence_status",
        "embedder_status",
        "anchor_status",
        "refresh_anchors",
        "classify_text",
        "classify_function",
        "index_function",
        "index_batch",
        "similar_functions",
        "semantic_search",
        "blackboard_search",
        "export_index_summary",
        "evidence_card",
    ],
    "analysis": [
        "get_options",
        "set_options",
        "set_processor",
        "set_loader_options",
        "set_architecture",
        "reanalyze",
        "plugin_run",
    ],
    "annotation": [
        "auto_comment",
        "auto_comment_function",
        "label_loops",
        "label_branches",
        "mark_dangerous",
        "annotate_constants",
        "tag_functions",
        "document_args",
        "mark_error_paths",
        "propagate_names",
        "cleanup",
        "validate",
        "get_context",
        "set_structured",
        "bulk_set",
        "export_md",
        "import_md",
        "summary",
    ],
    "batch": [],
    "binary_info": [
        "headers",
        "sections",
        "relocations",
        "resources",
        "debug_info",
        "compiler",
        "linker",
        "timestamps",
        "checksums",
        "overlay",
    ],
    "blackboard": [
        "policy_set",
        "policy_status",
        "policy_check",
        "phase_status",
        "phase_set",
        "phase_tick",
        "quest_board",
        "quest_complete",
        "memory_compile",
        "phase_finalize",
        "trace_ingest",
        "trace_run",
        "trace_status",
        "proposal_create",
        "proposal_list",
        "proposal_accept",
        "proposal_reject",
        "decision_card",
        "working_set",
        "state_health",
        "notes_export",
        "notes_import",
        "write",
        "read",
        "list",
        "search",
        "semantic_index",
        "semantic_rebuild",
        "related_by_behavior",
        "update",
        "delete",
        "clear",
        "stats",
        "prune",
        "merge",
        "contradict",
        "resolve",
        "next_target",
        "frontier",
        "coverage",
        "propagate_labels",
        "start_crawler",
        "stop_crawler",
        "crawler_status",
        "accept",
        "reject",
        "add_evidence",
        "calibrate",
        "campaign_summary",
        "auto_tag_propagate",
        "accept_proposal",
        "reject_proposal",
        "add_system",
        "add_struct",
        "add_gap",
        "fill_gap",
        "add_state_machine",
        "add_peripheral",
        "add_attack_surface",
        "kg_summary",
        "kg_systems",
        "kg_gaps",
        "kg_structs",
        "kg_state_machines",
        "kg_attack_surface",
        "kg_peripherals",
        "export_symbols",
        "import_symbols",
    ],
    "bookmarks": [
        "add",
        "list",
        "delete",
        "update",
        "clear",
        "find",
        "export",
    ],
    "bridge_search": [
        "search",
        "bridges",
    ],
    "bulk": [
        "rename",
        "comment",
        "apply_type",
        "rename_stack",
        "import_annotations",
        "export_annotations",
    ],
    "calc": [
        "eval",
        "offset",
        "convert",
        "resolve",
        "deref",
        "chain",
        "align",
        "bitops",
    ],
    "cfg_analysis": [
        "complexity",
        "loops",
        "branches",
        "paths",
        "dominators",
        "post_dominators",
        "back_edges",
        "natural_loops",
        "irreducible",
        "flatten_detect",
    ],
    "classify": [
        "function",
        "binary",
        "all_functions",
        "library_code",
        "wrappers",
        "callbacks",
        "initializers",
        "error_handlers",
        "hot_functions",
        "orphans",
        "induce_schema",
        "anchor_coverage",
    ],
    "code": [
        "decompile",
        "disasm",
        "xrefs_to",
        "xrefs_from",
        "xrefs_to_field",
        "callees",
        "callers",
        "blocks",
        "analyze",
        "callgraph",
        "export",
        "find_paths",
        "strings_in_func",
        "diff_functions",
        "semantic_decompile",
        "decomp_dataflow",
        "decompile_chain",
        "smart_decompile",
        "annotate",
        "explain",
        "json",
        "c_header",
        "prototypes",
        "csmini",
        "classic",
        "annotated",
    ],
    "colorize": [
        "set_func",
        "set_range",
        "set_insn",
        "get",
        "clear",
        "palette",
        "highlight_pattern",
    ],
    "compare": [
        "functions",
        "blocks",
        "apis",
        "strings",
        "constants",
        "structure",
        "semantics",
        "batch_compare",
        "find_clones",
        "changelog",
    ],
    "coverage": [
        "import_drcov",
        "import_lighthouse",
        "highlight",
        "report",
        "uncovered",
        "filter",
        "function_coverage",
        "gaps",
        "compare",
        "merge",
    ],
    "crypto_id": [
        "identify",
        "constants",
        "encoding",
        "checksums",
        "entropy_analysis",
        "aes_ni",
    ],
    "ctree": [
        "get",
        "traverse",
        "find_calls",
        "find_vars",
        "find_strings",
        "find_conditions",
        "get_logic_flow",
        "dominance_map",
        "var_dependency_graph",
    ],
    "data": [
        "functions",
        "globals",
        "strings",
        "imports",
        "exports",
        "lookup",
        "bulk_query",
        "capability_matrix",
        "string_xrefs",
    ],
    "data_ops": [
        "make_data",
        "make_array",
        "make_string",
        "undefine",
        "make_code",
        "cycle_data",
        "set_repr",
        "make_ptr",
    ],
    "debug": [
        "status",
        "start",
        "stop",
        "continue",
        "step_into",
        "step_over",
        "run_to",
        "run_until",
        "breakpoints",
        "add_bp",
        "del_bp",
        "enable_bp",
        "add_hw_bp",
        "add_watch",
        "regs",
        "set_reg",
        "reg_diff",
        "snapshot_regs",
        "threads",
        "modules",
        "callstack",
        "read_mem",
        "write_mem",
        "search_mem",
        "stack_dump",
        "mem_map",
        "bp_context",
        "trace_start",
        "trace_stop",
        "trace_read",
        "mem_diff",
        "read",
        "write",
        "rw",
        "execute",
    ],
    "deobfuscate": [
        "detect",
        "detect_encoding",
        "stack_strings",
        "dead_code",
        "api_hashing",
        "dynamic_dispatch",
        "anti_disasm",
        "decode_attempt",
    ],
    "entropy": [
        "section",
        "region",
        "packed_detect",
        "crypto_detect",
        "compare",
        "window",
        "summary",
    ],
    "export": [
        "listing",
        "html",
        "idc",
        "json",
        "sarif",
        "binexport",
        "headers",
        "redact",
    ],
    "filter": [
        "filter",
    ],
    "firmware_view": [
        "scan_region",
        "auto_retype",
        "pointer_sweep",
        "recommend",
        "table_candidates",
        "smart_carve",
        "rollback_last",
        "review_contradictions",
        "region_profile",
        "pointer_clusters",
        "carve_plan",
        "campaign",
        "segment_sweep",
        "multi_region_campaign",
        "campaign_checkpoint",
        "campaign_resume",
        "campaign_feedback",
        "fingerprint_index_sync",
        "fingerprint_index_query",
        "detect_load_address",
        "detect_vector_table",
        "detect_mmio",
        "rtos_scan",
        "triage_snapshot",
        "bootstrap",
    ],
    "fixups": [
        "list",
        "get",
        "add",
        "delete",
    ],
    "funcs": [
        "create",
        "delete",
        "set_flags",
        "info",
        "metrics",
        "find_similar",
        "suggest_names",
    ],
    "gadgets": [
        "rop",
        "jop",
        "cop",
        "syscall",
        "write_what_where",
        "stack_pivot",
        "shellcode_space",
        "mitigations",
        "seh_handlers",
        "pivot_chains",
        "classify_chain",
    ],
    "governance": [
        "check",
        "redact",
        "list_rules",
        "stats",
    ],
    "knowledge": [
        "chip_identify",
        "symbol_lookup",
        "import_symbols",
        "export_session",
        "chip_families",
    ],
    "graph": [
        "callgraph",
        "cfg",
        "dominators",
        "xref_graph",
        "call_chain",
        "common_callers",
        "common_callees",
        "hub_functions",
        "leaf_functions",
        "recursive",
        "dominator",
        "influence",
        "dependency_graph",
        "dead_functions",
    ],
    "history": [
        "undo",
        "redo",
        "list",
        "snapshot",
        "restore",
        "diff",
    ],
    "hooks": [
        "suggest",
        "generate_frida",
        "generate_detours",
        "find_targets",
        "inline_hooks",
    ],
    "idb": [
        "meta",
        "summary",
        "segments",
        "entrypoints",
        "bookmarks",
        "overview",
        "architecture_profile",
    ],
    "imports_deep": [
        "thunks",
        "delay",
        "forwarded",
        "ordinal",
        "api_sets",
        "resolve",
    ],
    "llm_helpers": [
        "bootstrap",
        "context_window",
        "function_digest",
        "binary_digest",
        "explain_address",
        "suggest_next",
        "progress_report",
        "focus_area",
        "question_answer",
        "guided_analysis",
        "cheatsheet",
        "compact",
        "enrich",
        "intent_tool_compiler",
        "adaptive_query_planner",
        "token_aware_context_optimizer",
        "cross_call_variable_resolver",
        "evidence_weighted_response_assembler",
        "uncertainty_propagation_engine",
        "multi_granularity_retrieval_layer",
        "semantic_chunking_for_decompiled_code",
        "question_type_router",
        "interactive_clarification_protocol",
        "behavioral_signature_search",
        "cross_artifact_correlation_search",
        "temporal_search_replay",
        "search_hypothesis_sandbox",
        "path_constrained_search",
        "argument_semantics_search",
        "decompile_disasm_consistency_search",
        "near_miss_search_ranking",
        "persistent_search_collections",
        "auto_expansion_search_chains",
        "function_role_classifier",
        "global_state_influence_mapper",
        "api_contract_extractor",
        "interprocedural_data_lineage_graph",
        "semantic_diff_explainer",
        "dangerous_pattern_explainer",
        "binary_capability_matrix_builder",
        "execution_hypothesis_generator",
        "patch_impact_forecaster",
        "safe_idapython_orchestration_runtime",
        "script_template_marketplace_layer",
        "auto_script_synthesis_from_intent",
        "script_output_schema_enforcer",
        "long_running_job_manager",
        "cross_session_script_memory",
        "privilege_scope_guardrails_for_scripts",
        "script_to_tool_promotion_pipeline",
        "experiment_harness_for_script_variants",
        "idapython_provenance_recorder",
        "investigation_playbook_engine",
        "next_best_action_recommender",
        "analysis_dead_end_detector",
        "workset_intelligence_capsules",
        "contradiction_tracker",
        "review_queue_for_ai_edits",
        "case_narrative_composer",
        "cost_latency_optimizer",
        "trust_verification_layer",
        "learning_feedback_loop",
    ],
    "lumina": [
        "pull",
        "push",
        "status",
        "history",
        "search",
        "get_metadata",
    ],
    "memory": [
        "read",
        "write",
        "hexdump",
        "search",
        "compare",
        "pointers",
        "find_pointers",
        "entropy",
        "strings",
        "struct_walk",
        "histogram",
        "read_file",
        "write_file",
        "bytes",
        "u8",
        "u16",
        "u32",
        "u64",
        "s8",
        "s16",
        "s32",
        "s64",
        "f32",
        "f64",
        "ptr",
        "string",
    ],
    "microcode": [
        "get",
        "blocks",
        "instructions",
        "def_use_graph",
    ],
    "misc": [
        "python",
        "idc",
        "load_sig",
        "cache_stats",
        "plugin_list",
    ],
    "modify": [
        "rename",
        "comment",
        "set_type",
        "patch_asm",
    ],
    "nav": [
        "goto",
        "cursor",
        "interesting",
        "semantic_goto",
    ],
    "patterns": [
        "generate",
        "match",
        "list_sigs",
        "apply_sig",
        "create_sig",
        "matched",
        "yara_from_func",
        "flirt_generate",
        "match_yara",
    ],
    "predictor": [
        "suggest_next_tool",
        "detect_stuck",
        "suggest_focus",
        "suggest_next_address",
        "risk_of_stall",
        "recommend_bundle",
        "explain_decision",
        "feedback",
    ],
    "project": [
        "save",
        "close",
        "open",
        "load_binary",
        "list_recent",
        "get_cwd",
        "set_cwd",
        "list_dir",
        "exists",
        "evidence_graph",
        "knowledge_merge",
        "confidence_model",
        "replay_pipeline",
        "hypothesis_tracker",
        "temporal_reasoning",
        "semantic_artifact_diff",
        "ai_governance",
        "knowledge_debt",
        "casefile_export",
    ],
    "protocol": [
        "detect",
        "parsers",
        "serializers",
        "handlers",
        "endpoints",
        "tls_config",
        "socket_flow",
        "packet_struct",
        "magic_numbers",
        "state_machine",
    ],
    "query": [
        "data",
        "search",
        "idb",
        "code",
        "types",
        "imports_deep",
        "symbols",
        "patterns",
        "nl",
        "nl_batch",
    ],
    "schemaboot": [
        "ingest",
        "query",
        "refresh",
        "stats",
        "delete",
        "get",
    ],
    "search": [
        "text",
        "bytes",
        "regex",
        "immediate",
        "code_pattern",
        "next",
        "all",
        "structured",
        "string",
        "name",
        "comment",
        "mnemonic",
        "operand",
        "insns",
        "instruction",
        "decompiled",
        "constants",
        "semantic",
        "smart_bundle",
        "func_by_sig",
        "vulnerable",
        "api",
        "callees",
        "callers",
        "code_ref",
        "data_ref",
        "export",
        "find",
        "nl",
        "behavior",
        "query_lang",
        "summary",
        "type",
    ],
    "segments": [
        "list",
        "add",
        "delete",
        "set_attr",
        "set_perms",
        "move",
        "info",
        "analyze",
        "find_code",
        "find_data",
        "compare",
        "merge",
    ],
    "session": [
        "discover",
        "create",
        "get",
        "list",
        "switch",
        "close",
        "status",
        "rebuild",
        "update",
        "rename",
        "duplicate",
        "export_session",
        "import_session",
        "archive",
        "unarchive",
        "tag",
        "untag",
        "find_by_tag",
        "add_note",
        "clear_notes",
        "cleanup_stale",
        "health",
        "stats",
        "validate",
        "bulk_delete",
        "bulk_tag",
        "search_notes",
        "recent",
        "oldest",
        "snapshot",
        "restore_snapshot",
        "merge",
        "macro_set",
        "macro_get",
        "macro_list",
        "macro_delete",
        "macro_run",
        "recent_workset",
        "crystallize_skill",
        "rate_skill",
        "list_skills",
        "suggest_strategy",
        "log_activity",
        "get_activity_log",
        "notebook_append",
        "notebook_read",
        "notebook_section",
        "track_hypothesis",
        "confirm_hypothesis",
        "refute_hypothesis",
        "list_hypotheses",
        "get_phase",
        "advance_phase",
        "dashboard",
        "link",
        "cross_reference",
        "list_snapshots",
    ],
    "stack_analysis": [
        "frame",
        "buffers",
        "canary",
        "alignment",
        "spills",
        "usage",
        "variables",
        "arrays",
        "uninitialized",
        "summary",
    ],
    "string_ops": [
        "decode_all",
        "find_urls",
        "find_paths",
        "find_registry",
        "find_ips",
        "find_emails",
        "find_commands",
        "encoding_stats",
        "multilingual",
        "suspicious",
        "find_xrefs",
        "find_stack_strings",
        "find_base64",
        "find_api_keys",
        "find_configs",
        "find_c2",
        "find_databases",
        "find_crypto_addrs",
        "entropy_rank",
        "score_c2",
        "indicators",
        "persistence",
        "evasion",
        "ioc_extract",
    ],
    "summarize": [
        "binary",
        "function",
        "segment",
        "imports_by_category",
        "strings_by_category",
        "complexity",
        "call_hierarchy",
        "data_flow",
        "security_posture",
        "statistics",
        "report",
    ],
    "symbols": [
        "load_pdb",
        "load_dwarf",
        "status",
        "apply",
        "export",
    ],
    "taint": [
        "sources",
        "sinks",
        "trace",
        "report",
        "paths",
    ],
    "threat_hunt": [
        "run",
        "malware",
        "vuln",
        "tracing",
        "findings",
        "quick",
        "deep",
        "legacy",
    ],
    "trace_analysis": [
        "import_trace",
        "analyze_coverage",
        "find_loops",
        "extract_api_calls",
        "basic_blocks_hit",
        "execution_timeline_graph",
        "cross_run_diff",
        "coverage_debug_plan",
        "anti_analysis_detect",
        "trace_entropy",
        "api_sequence",
        "loop_analysis",
        "get",
        "clear",
        "set_options",
        "static_trace",
        "decrypt_strings",
        "eval_expr",
    ],
    "truncation": [
        "continue",
    ],
    "types": [
        "list",
        "get",
        "set_prototype",
        "parse_decl",
        "declare",
        "apply",
        "search_structs",
        "infer",
        "read_struct",
        "import_header",
        "diff",
        "visualize",
        "propagate",
        "enum_values",
        "type_graph",
    ],
    "wiki": [
        "list_topics",
        "read",
        "search",
        "semantic_search",
        "index",
        "sections",
        "suggest",
    ],
    "workflow": [
        "audit_plan",
        "execute_plan",
        "prioritize",
        "compose",
        "estimate",
        "explain",
        "plan",
        "catalog",
        "triage_fast",
        "malware_deep",
        "vuln_audit",
        "recon_sweep",
        "patch_review",
    ],
    "yara_hunt": [
        "scan",
        "compile",
        "list_rules",
        "match_context",
        "extract_strings",
        "xref_matches",
    ],
}

TOOL_ARG_SCHEMAS = {
    "session": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["session"]},
        "binary_path": {"type": "string", "description": "Path to target binary"},
        "force_new": {
            "type": "boolean",
            "description": "Force creation of a new session even if one exists",
        },
        "analysis_options": {
            "type": "object",
            "description": "Advanced analysis payload. Preferred for architecture/loader config at session creation.",
        },
        "architecture": {
            "type": "object",
            "description": "Canonical preload architecture block for create/update (processor, bitness, endian, loader, loader_options, flags).",
        },
        "ida_args": {"type": ["string", "array"], "items": {"type": "string"}},
        "session_id": {"type": "string", "description": "Session ID for switch/close"},
        "query": {
            "type": "string",
            "description": "Filter sessions by name/path (supports regex, glob, substring)",
        },
        "processor": {"type": "string", "description": "Processor name (e.g. arm, mipsl, tricore)."},
        "flags": {"type": "integer"},
        "loader": {"type": "string", "description": "Loader name used before initial analysis."},
        "value": {"type": ["string", "object"], "description": "Loader option payload alias (same as loader_options)."},
        "loader_options": {"type": ["string", "object"], "description": "Loader option payload applied before analysis."},
        "bitness": {"type": "integer", "description": "Target bitness: 16, 32, or 64."},
        "endian": {"type": "string", "description": "Target endianness: le/little or be/big."},
        "reanalyze": {"type": "boolean"},
        "options": {"type": "object"},
        "analysis_actions": {"type": "array", "items": {"type": "object"}},
        "apply_once": {"type": "boolean"},
        "recover": {"type": "boolean"},
        "backup_on_recover": {"type": "boolean"},
        "aggressive_cleanup": {"type": "boolean"},
        "start": {"type": ["string", "integer"]},
        "end": {"type": ["string", "integer"]},
        "baseaddr": {"type": ["string", "integer"]},
        "start_ea": {"type": ["string", "integer"]},
        "min_ea": {"type": ["string", "integer"]},
        "max_ea": {"type": ["string", "integer"]},
        "limit": {
            "type": "integer",
            "description": "Max sessions to return (list action)",
        },
        "offset": {
            "type": "integer",
            "description": "Skip first N sessions (list action)",
        },
        "tags": {
            "type": ["array", "string"],
            "items": {"type": "string"},
            "description": "Tags for the session (create action). Comma-separated string or array.",
        },
        "notes": {
            "type": "string",
            "description": "Free-form notes for the session (create action).",
        },
        "note": {
            "type": "string",
            "description": "Single note payload for add_note action.",
        },
        "name": {
            "type": "string",
            "description": "Name for macro_* actions or rename action.",
        },
        "macro": {
            "type": "string",
            "description": "Alias for macro name in macro_* actions.",
        },
        "data": {"type": "object", "description": "Macro payload for macro_set."},
        "macro_data": {
            "type": "object",
            "description": "Alias for macro payload in macro_set.",
        },
        "run_action": {
            "type": "string",
            "description": "Session action to execute for macro_run (default from macro or create).",
        },
        "n": {
            "type": "integer",
            "description": "Count for recent/oldest/recent_workset actions.",
        },
        "include_bookmarks": {
            "type": "boolean",
            "description": "Include bookmark entries in recent_workset.",
        },
        "include_items": {
            "type": "boolean",
            "description": "Include structured items in recent_workset response.",
        },
        "verbose": {
            "type": "boolean",
            "description": "Include per-runtime details for health action.",
        },
    },
    "truncation": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["truncation"]},
        "token": {"type": "string"},
        "field": {"type": "string"},
        "offset": {"type": "integer"},
        "count": {"type": "integer"},
    },
    "bookmarks": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["bookmarks"]},
        "addr": {"type": "string"},
        "id": {"type": "integer"},
        "name": {"type": "string"},
        "notes": {"type": "string"},
        "category": {"type": "string"},
        "priority": {"type": "integer"},
        "tags": {"type": ["array", "string"], "items": {"type": "string"}},
        "query": {"type": "string"},
    },
    "funcs": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["funcs"]},
        "addr": {"type": "string"},
        "end": {"type": "string"},
        "name": {"type": "string"},
        "flags": {"type": "integer"},
        "force": {"type": "boolean"},
        "comment": {"type": "string"},
        "repeatable": {"type": "boolean"},
        "query": {"type": "string"},
        "offset": {"type": "integer"},
        "count": {"type": "integer"},
        "named_only": {"type": "boolean"},
        "include_prototype": {"type": "boolean"},
        "include_stack": {"type": "boolean"},
        "include_items": {"type": "boolean"},
        "include_xrefs": {"type": "boolean"},
    },
    "calc": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["calc"]},
        "expr": {"type": "string"},
        "addr": {"type": "string"},
        "target": {"type": "string"},
        "value": {"type": ["string", "integer"]},
        "bit_op": {"type": "string"},
        "type": {"type": "string"},
        "size": {"type": "integer"},
        "offsets": {"type": ["array", "string"], "items": {"type": "string"}},
    },
    "memory": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["memory"]},
        "addr": {"type": "string"},
        "type": {
            "type": "string",
            "enum": [
                "bytes",
                "u8",
                "u16",
                "u32",
                "u64",
                "s8",
                "s16",
                "s32",
                "s64",
                "f32",
                "f64",
                "ptr",
                "string",
            ],
        },
        "size": {"type": "integer"},
        "data": {"type": "string"},
        "path": {"type": "string", "description": "File path for read_file/write_file"},
        "content": {"type": "string", "description": "Content to write for write_file"},
        "encoding": {
            "type": "string",
            "description": "File encoding (default: utf-8). Use 'binary' for hex-encoded binary data.",
        },
    },
    "misc": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["misc"]},
        "expr": {
            "type": "string",
            "description": "Python expression or IDC script to evaluate",
        },
        "code": {"type": "string", "description": "Multi-line Python code to execute"},
        "name": {"type": "string", "description": "Signature name for load_sig"},
    },
    "analysis": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["analysis"]},
        "options": {"type": "object"},
        "processor": {"type": "string"},
        "flags": {"type": "integer"},
        "loader": {"type": "string"},
        "value": {"type": ["string", "object"]},
        "bitness": {"type": "integer"},
        "endian": {"type": "string"},
        "start": {"type": "string"},
        "end": {"type": "string"},
        "name": {"type": "string", "description": "Plugin name for plugin_run"},
        "arg": {"type": "integer", "description": "Plugin argument for plugin_run"},
    },
    "data": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["data"]},
        "query": {"type": "string"},
        "offset": {"type": "integer"},
        "count": {"type": "integer"},
        "include_prototype": {"type": "boolean"},
        "include_xrefs": {"type": "boolean"},
        "min_size": {"type": "integer"},
        "named_only": {"type": "boolean"},
        "items": {"type": "array", "items": {"type": "object"}},
    },
    "search": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["search"]},
        "pattern": {"type": "string"},
        "query": {"type": "string"},
        "addr": {"type": "string"},
        "limit": {"type": "integer"},
        "offset": {"type": "integer"},
        "start": {"type": "string"},
        "end": {"type": "string"},
        "case_sensitive": {"type": "boolean"},
        "include_context": {"type": "boolean"},
        "include_items": {"type": "boolean"},
        "include_breakdown": {"type": "boolean"},
        "timeout_ms": {"type": "integer"},
        "max_functions": {"type": "integer"},
        "sample": {"type": "boolean"},
        "sample_max_funcs": {"type": "integer"},
    },
    "threat_hunt": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["threat_hunt"]},
        "legacy_tool": {
            "type": "string",
            "description": "Legacy tool name to emulate (for action='legacy').",
        },
        "legacy_action": {
            "type": "string",
            "description": "Legacy action to inherit/route (for action='legacy').",
        },
        "profile": {
            "type": "string",
            "enum": ["quick", "balanced", "deep"],
            "description": "Pipeline depth profile.",
        },
        "query": {
            "type": "string",
            "description": "Optional focus query for post-filtering and relevance scoring.",
        },
        "addr": {
            "type": "string",
            "description": "Optional address focus for underlying scanners where supported.",
        },
        "include_tracing": {
            "type": "boolean",
            "description": "Include trace/coverage analysis steps.",
        },
        "include_malware": {
            "type": "boolean",
            "description": "Include malware-behavior analysis steps.",
        },
        "include_vuln": {
            "type": "boolean",
            "description": "Include vulnerability analysis steps.",
        },
        "include_evidence": {
            "type": "boolean",
            "description": "Include compact raw per-step payloads for auditability.",
        },
        "limit": {
            "type": "integer",
            "description": "Global max findings to return after dedupe/ranking.",
        },
        "max_steps": {
            "type": "integer",
            "description": "Safety cap for total orchestrated tool calls.",
        },
        "scan_profile": {
            "type": "string",
            "enum": ["quick", "balanced", "deep"],
            "description": "Forwarded depth profile to threat_hunt.",
        },
        "severity": {
            "type": "string",
            "enum": ["critical", "high", "medium", "low"],
            "description": "Optional severity filter for vulnerability findings.",
        },
        "legacy_passthrough": {
            "type": "boolean",
            "description": "For action='legacy', execute exact mapped legacy action in consolidated flow and include mapping metadata.",
        },
    },
    "predictor": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["predictor"]},
        "session_id": {
            "type": "string",
            "description": "Optional session ID. If omitted, active session is used.",
        },
        "context": {
            "type": "string",
            "description": "Optional context text to bias suggestions.",
        },
        "limit": {
            "type": "integer",
            "minimum": 1,
            "maximum": 20,
            "description": "Maximum suggestions to return.",
        },
        "recent_n": {
            "type": "integer",
            "minimum": 5,
            "maximum": 200,
            "description": "Recent activity window for sequence modeling.",
        },
        "target_tool": {
            "type": "string",
            "description": "Target tool for explain_decision action.",
        },
        "target_action": {
            "type": "string",
            "description": "Target action for explain_decision action.",
        },
        "tool": {
            "type": "string",
            "description": "Tool name for predictor feedback action.",
        },
        "outcome": {
            "type": "string",
            "enum": ["helpful", "not_helpful"],
            "description": "Feedback outcome for predictor(action='feedback').",
        },
    },
    "workflow": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["workflow"]},
        "planned_calls": {
            "type": "array",
            "items": {"type": "object"},
            "description": "For action='prioritize'/'execute_plan'/'audit_plan': optional dry-run call list to reorder, execute, or validate.",
        },
        "priority_mode": {
            "type": "string",
            "enum": ["original", "coverage", "risk_first"],
            "description": "For action='prioritize': sorting strategy for dry-run plan ordering.",
        },
        "continue_on_error": {
            "type": "boolean",
            "description": "For action='execute_plan': continue executing later calls when one call fails.",
        },
        "max_steps": {
            "type": "integer",
            "minimum": 1,
            "maximum": 200,
            "description": "For action='execute_plan': maximum calls to execute from the provided/generated plan.",
        },
        "workflow_actions": {
            "type": ["array", "string"],
            "items": {"type": "string"},
            "description": "For action='compose': list of workflow actions to merge into one dry-run plan.",
        },
        "workflow_action": {
            "type": "string",
            "description": "For action='plan': target workflow action to preview (for example triage_fast or recon_sweep).",
        },
        "addr": {
            "type": "string",
            "description": "Optional address focus for the workflow.",
        },
        "limit": {
            "type": "integer",
            "minimum": 1,
            "maximum": 100,
            "description": "Max findings per sub-step.",
        },
        "profile": {
            "type": "string",
            "enum": ["quick", "balanced", "deep"],
            "description": "Depth profile override for underlying pipelines.",
        },
        "dry_run": {
            "type": "boolean",
            "description": "When true, return the planned calls and workflow metadata without executing tool steps.",
        },
        "include_tools": {
            "type": ["array", "string"],
            "items": {"type": "string"},
            "description": "Optional allow-list of tool names to keep in the generated plan.",
        },
        "exclude_tools": {
            "type": ["array", "string"],
            "items": {"type": "string"},
            "description": "Optional deny-list of tool names to remove from the generated plan.",
        },
    },
    "segments": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["segments"]},
        "start": {"type": "string"},
        "end": {"type": "string"},
        "name": {"type": "string"},
        "sclass": {"type": "string"},
        "attr": {"type": "string"},
        "value": {"type": ["string", "integer"]},
        "offset": {"type": "integer"},
        "count": {"type": "integer"},
    },
    "agent": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["agent"]},
        "addr": {"type": "string"},
        "query": {"type": "string"},
        "depth": {"type": "integer"},
        "include_pseudocode": {"type": "boolean"},
        "max_items": {"type": "integer"},
        "use_cache": {"type": "boolean"},
    },
    "intelligence": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["intelligence"]},
        "addr": {"type": "string"},
        "query": {"type": "string"},
        "max_items": {"type": "integer"},
        "threshold": {"type": "number"},
        "top_k": {"type": "integer"},
        "block": {"type": "boolean"},
        "probe": {"type": "boolean"},
        "deep_hash": {"type": "boolean"},
        "limit": {"type": "integer"},
    },
    "query": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["query"]},
        "subaction": {"type": "string"},
        "args": {"type": "object"},
    },
    "idb": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["idb"]},
        "offset": {"type": "integer"},
        "count": {"type": "integer"},
    },
    "code": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["code"]},
        "addrs": {"type": ["array", "string"], "items": {"type": "string"}},
        "addr": {"type": "string"},
        "max_items": {"type": "integer"},
        "max_depth": {"type": "integer"},
        "format": {"type": "string"},
        "disasm_style": {"type": "string", "enum": ["csmini", "classic", "annotated"]},
        "include_bytes": {"type": "boolean"},
        "end": {"type": "string"},
        "limit": {"type": "integer"},
        "field_name": {"type": "string"},
        "target": {"type": "string"},
    },
    "ctree": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["ctree"]},
        "addr": {"type": "string"},
        "query": {"type": "string"},
        "depth": {"type": "integer"},
    },
    "entropy": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["entropy"]},
        "addr": {"type": "string"},
        "size": {"type": "integer"},
        "threshold": {"type": "number"},
        "end_addr": {"type": "string"},
        "window": {"type": "integer"},
        "step": {"type": "integer"},
        "limit": {"type": "integer"},
    },
    "gadgets": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["gadgets"]},
        "addr": {"type": "string"},
        "query": {"type": "string"},
        "limit": {"type": "integer"},
        "max_insns": {"type": "integer"},
        "source_actions": {"type": ["array", "string"], "items": {"type": "string"}},
        "source_limit": {"type": "integer"},
        "rebuild_index": {"type": "boolean"},
        "min_score": {"type": "integer"},
        "offset": {"type": "integer"},
    },
    "wiki": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["wiki"]},
        "topic": {"type": "string"},
        "query": {"type": "string"},
        "section": {"type": "string"},
        "lines": {
            "type": "string",
            "description": "Line selector such as '10-40', '25', '10-', or '-40'.",
        },
        "line_start": {"type": "integer"},
        "line_end": {"type": "integer"},
        "offset": {"type": "integer"},
        "limit": {"type": "integer"},
        "max_results": {"type": "integer"},
        "category": {"type": ["string", "array"], "items": {"type": "string"}},
        "fuzzy": {"type": "boolean"},
        "strict_topic": {"type": "boolean"},
        "include_related": {"type": "boolean"},
        "include_snippets": {"type": "boolean"},
        "context_lines": {"type": "integer"},
        "verbose": {
            "type": "boolean",
            "description": "Include full structural metadata in wiki responses.",
        },
    },
    "bulk": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["bulk"]},
        "items": {"type": "array", "items": {"type": "object"}},
        "path": {"type": "string"},
        "continue_on_error": {"type": "boolean"},
    },
    "batch": {
        "calls": {
            "type": "array",
            "items": {
                "type": ["object", "string"],
                "description": "Each item can be 'tool:action', {name, arguments}, or {name, action, ...args}.",
            },
        },
        "script": {"type": "string", "description": "Macro DSL script. Alternative to 'calls'."},
        "stop_on_error": {"type": "boolean"},
        "dry_run": {"type": "boolean"},
        "template": {"type": "string", "description": "Predefined template name"},
        "template_vars": {"type": "object", "description": "Variables for template expansion"},
    },
    "schemaboot": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["schemaboot"]},
        "constraints": {"type": "object", "description": "Structured query constraints"},
        "addr": {"type": "string", "description": "Function address for get/refresh"},
        "limit": {"type": "integer", "description": "Max results"},
        "offset": {"type": "integer", "description": "Skip first N results"},
        "order_by": {"type": "string", "description": "Column to order by (e.g., 'entropy DESC')"},
        "include_apis": {"type": "boolean", "description": "Include API list in results"},
        "include_strings": {"type": "boolean", "description": "Include string refs in results"},
    },
    "bridge_search": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["bridge_search"]},
        "query_constraints": {"type": "object", "description": "SchemaBoot-style constraints for seed selection"},
        "func_ea": {"type": "string", "description": "Hex address of seed function (for action='bridges')"},
        "func_name": {"type": "string", "description": "Name of seed function (for action='bridges')"},
        "bridge_types": {"type": "array", "items": {"type": "string"}, "description": "Bridge types: ['apis'], ['strings'], or ['apis', 'strings']"},
        "top_k": {"type": "integer", "description": "Max candidates to return"},
        "hops": {"type": "integer", "description": "Number of hops (2=standard, >2=extended)"},
    },
    "blackboard": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["blackboard"]},
        "entry_id": {"type": "string", "description": "Entry ID for read/update/delete"},
        "title": {"type": "string", "description": "Title for write/update"},
        "content": {"type": "string", "description": "Content/body text"},
        "category": {"type": "string", "description": "Category (default: general)"},
        "addr": {"type": "string", "description": "Associated address"},
        "query": {"type": "string", "description": "Semantic/behavior query for search and related_by_behavior"},
        "tags": {"type": "array", "items": {"type": "string"}, "description": "Tags for categorization"},
        "confidence": {"type": "number", "description": "Confidence score 0-1"},
        "tag": {"type": "string", "description": "Filter by single tag"},
        "min_confidence": {"type": "number", "description": "Minimum confidence filter"},
        "limit": {"type": "integer", "description": "Max entries to return"},
        "top_k": {"type": "integer", "description": "Top-K results for semantic retrieval"},
        "threshold": {"type": "number", "description": "Similarity threshold for semantic retrieval"},
        "include_resolved": {"type": "boolean", "description": "Include resolved entries in semantic retrieval"},
        "include_contradicted": {"type": "boolean", "description": "Include contradicted entries in semantic retrieval"},
        "force": {"type": "boolean", "description": "Force semantic_rebuild to re-embed all matching entries"},
        "offset": {"type": "integer", "description": "Pagination offset"},
        "db_path": {"type": "string", "description": "Override path to blackboard SQLite DB"},
    },
    "filter": {
        "data": {"type": "object", "description": "Tool output dict to filter"},
        "query": {"type": "string", "description": "JQ-like filter expression (e.g. '.functions[?size > 100] | first(10)')"},
    },
    "fixups": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["fixups"]},
        "addr": {"type": "string", "description": "Address of the fixup"},
        "target": {"type": "string", "description": "Target address (for add)"},
        "fixup_type": {"type": "integer", "description": "Fixup type id (processor specific)"},
        "start": {"type": "string", "description": "Start address for list range"},
        "end": {"type": "string", "description": "End address for list range"},
        "offset": {"type": "integer", "description": "Pagination offset"},
        "count": {"type": "integer", "description": "Max entries (0=all)"},
    },
    "governance": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["governance"]},
        "operation_type": {"type": "string", "description": "Operation type for check: patch, comment, rename, type_change, execution, annotation"},
        "addr": {"type": "string", "description": "Target address for the operation"},
        "proposed_value": {"type": "string", "description": "The proposed value to check or redact"},
        "context": {"type": "object", "description": "Optional context dict for governance check"},
        "metadata": {"type": "object", "description": "Optional metadata dict for governance check"},
    },
    "knowledge": {
        "action": {"type": "string", "enum": TOOL_ACTIONS["knowledge"]},
        "query": {"type": "string", "description": "Fuzzy text query for symbol lookup"},
        "min_confidence": {"type": "number", "description": "Minimum confidence threshold for symbol import"},
        "limit": {"type": "integer", "description": "Result limit"},
        "db_path": {"type": "string", "description": "Override path to symbol knowledge SQLite DB"},
        "chip_family": {"type": "string", "description": "Optional chip family tag for export_session"},
        "session_id": {"type": "string", "description": "Optional source session identifier for export_session"},
    },
}
